### PR TITLE
Add example of Go generics

### PR DESCRIPTION
**Pull request by jiasir**
# Changes
* Translate generics to Chinese
* Update builder and go version to 1.18

### CODE REVIEW

**Comment by everyx** [comment]
@jiasir 谢谢你的 PR，可以同步更新一下以下文件么？

https://github.com/gobyexample-cn/gobyexample/blob/640ec4c0f4c29292b8eefc6b36771a16f766b55b/README.md?plain=1#L91

https://github.com/gobyexample-cn/gobyexample/blob/640ec4c0f4c29292b8eefc6b36771a16f766b55b/PROGRESS.md?plain=1#L7

**Comment by jiasir** [comment]
Thanks @everyx ! `README.md` and `PROGRESS.md` have been updated.

**Comment by everyx** [comment]
> Thanks @everyx ! `README.md` and `PROGRESS.md` have been updated.

@jiasir 忘了提到了，[examples.txt](https://github.com/gobyexample-cn/gobyexample/blob/master/examples.txt) 也是需要同步更新的

**Comment by jiasir** [comment]
@everyx Done, thanks!

**Pull request merged**
